package codigo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rioja
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    GestorConexion gestor = new GestorConexion();

    public VentanaPrincipal() {
        initComponents();
        BotonApagar.setEnabled(false);
        BotonFecha.setEnabled(false);
        BotonFechaBorrar.setEnabled(false);
        BotonDatosAlbum.setEnabled(false);
        BotonConsultarAlbum.setEnabled(false);
        BotonConsultarCanciones.setEnabled(false);
        BotonConsultasPrepared.setEnabled(false);
        BotonCommit.setEnabled(false);
        BotonDatosCanciones.setEnabled(false);
        
        salidaConsultas.setVisible(false);    
        salidaConsultas.setSize(300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salidaConsultas = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        salidaConsultasTexto = new javax.swing.JTextArea();
        fondoColor = new javax.swing.JPanel();
        darkMode = new javax.swing.JToggleButton();
        BotonApagar = new javax.swing.JButton();
        BotonEncender = new javax.swing.JButton();
        BotonFecha = new javax.swing.JButton();
        BotonFechaBorrar = new javax.swing.JButton();
        BotonDatosAlbum = new javax.swing.JButton();
        BotonConsultarAlbum = new javax.swing.JButton();
        BotonConsultarCanciones = new javax.swing.JButton();
        BotonConsultasPrepared = new javax.swing.JButton();
        BotonCommit = new javax.swing.JButton();
        BotonDatosCanciones = new javax.swing.JButton();
        insertarDatos = new javax.swing.JLabel();
        nombreCancion = new javax.swing.JLabel();
        nombreAutor = new javax.swing.JLabel();
        nombreNCanciones = new javax.swing.JLabel();
        insertarFecha = new javax.swing.JLabel();
        consultarDatos = new javax.swing.JLabel();
        consultaAutorLabel = new javax.swing.JLabel();
        consultaCancionLabel = new javax.swing.JLabel();
        insertarDatosCancion = new javax.swing.JLabel();
        nombreCancionCanciones = new javax.swing.JLabel();
        nombreAutorCanciones = new javax.swing.JLabel();
        nombreDuracion = new javax.swing.JLabel();
        nombreCancionField = new javax.swing.JTextField();
        nombreAutorField = new javax.swing.JTextField();
        nombreNCancionesField = new javax.swing.JTextField();
        consultaCancion = new javax.swing.JTextField();
        consultaAutor = new javax.swing.JTextField();
        nombreCancionCancionesField = new javax.swing.JTextField();
        nombreAutorCancionesField = new javax.swing.JTextField();
        nombreDuracionField = new javax.swing.JTextField();

        salidaConsultasTexto.setColumns(20);
        salidaConsultasTexto.setRows(5);
        jScrollPane1.setViewportView(salidaConsultasTexto);

        javax.swing.GroupLayout salidaConsultasLayout = new javax.swing.GroupLayout(salidaConsultas.getContentPane());
        salidaConsultas.getContentPane().setLayout(salidaConsultasLayout);
        salidaConsultasLayout.setHorizontalGroup(
            salidaConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );
        salidaConsultasLayout.setVerticalGroup(
            salidaConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoColor.setBackground(new java.awt.Color(102, 102, 102));

        darkMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/light_16.png"))); // NOI18N
        darkMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        darkMode.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/dark_16.png"))); // NOI18N
        darkMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                darkModeMousePressed(evt);
            }
        });
        darkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeActionPerformed(evt);
            }
        });

        BotonApagar.setBackground(new java.awt.Color(0, 0, 0));
        BotonApagar.setForeground(new java.awt.Color(204, 204, 204));
        BotonApagar.setText("Apagar");
        BotonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonApagarActionPerformed(evt);
            }
        });

        BotonEncender.setBackground(new java.awt.Color(0, 0, 0));
        BotonEncender.setForeground(new java.awt.Color(204, 204, 204));
        BotonEncender.setText("Encender/Actualizar");
        BotonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncenderActionPerformed(evt);
            }
        });

        BotonFecha.setBackground(new java.awt.Color(0, 0, 0));
        BotonFecha.setForeground(new java.awt.Color(204, 204, 204));
        BotonFecha.setText("Añadir fecha");
        BotonFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFechaActionPerformed(evt);
            }
        });

        BotonFechaBorrar.setBackground(new java.awt.Color(0, 0, 0));
        BotonFechaBorrar.setForeground(new java.awt.Color(204, 204, 204));
        BotonFechaBorrar.setText("Borrar fecha");
        BotonFechaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFechaBorrarActionPerformed(evt);
            }
        });

        BotonDatosAlbum.setBackground(new java.awt.Color(0, 0, 0));
        BotonDatosAlbum.setForeground(new java.awt.Color(204, 204, 204));
        BotonDatosAlbum.setText("Insertar datos");
        BotonDatosAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDatosAlbumActionPerformed(evt);
            }
        });

        BotonConsultarAlbum.setText("Consultar Albumes");
        BotonConsultarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarAlbumActionPerformed(evt);
            }
        });

        BotonConsultarCanciones.setText("Consultar Canciones");
        BotonConsultarCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarCancionesActionPerformed(evt);
            }
        });

        BotonConsultasPrepared.setText("Consultar datos");
        BotonConsultasPrepared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultasPreparedActionPerformed(evt);
            }
        });

        BotonCommit.setText("Insertar Con Commit");
        BotonCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCommitActionPerformed(evt);
            }
        });

        BotonDatosCanciones.setBackground(new java.awt.Color(0, 0, 0));
        BotonDatosCanciones.setForeground(new java.awt.Color(204, 204, 204));
        BotonDatosCanciones.setText("Insertar datos");
        BotonDatosCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDatosCancionesActionPerformed(evt);
            }
        });

        insertarDatos.setBackground(new java.awt.Color(0, 0, 0));
        insertarDatos.setForeground(new java.awt.Color(204, 204, 204));
        insertarDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insertarDatos.setText("Insertar Datos en Album");
        insertarDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        insertarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertarDatos.setOpaque(true);

        nombreCancion.setText("Album:");

        nombreAutor.setText("Autor:");

        nombreNCanciones.setText("Canciones:");

        insertarFecha.setBackground(new java.awt.Color(0, 0, 0));
        insertarFecha.setForeground(new java.awt.Color(204, 204, 204));
        insertarFecha.setText("Añadir/Borrar fecha");
        insertarFecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        insertarFecha.setOpaque(true);

        consultarDatos.setBackground(new java.awt.Color(0, 0, 0));
        consultarDatos.setForeground(new java.awt.Color(204, 204, 204));
        consultarDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultarDatos.setText("Consultar Datos Album");
        consultarDatos.setAlignmentX(1.0F);
        consultarDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultarDatos.setOpaque(true);

        consultaAutorLabel.setText("Autor:");

        consultaCancionLabel.setText("Cancion:");

        insertarDatosCancion.setBackground(new java.awt.Color(0, 0, 0));
        insertarDatosCancion.setForeground(new java.awt.Color(204, 204, 204));
        insertarDatosCancion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insertarDatosCancion.setText("Insertar Datos en Canciones");
        insertarDatosCancion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        insertarDatosCancion.setOpaque(true);

        nombreCancionCanciones.setText("Cancion:");

        nombreAutorCanciones.setText("Autor:");

        nombreDuracion.setText("Duracion:");

        nombreCancionField.setBackground(new java.awt.Color(0, 0, 0));
        nombreCancionField.setForeground(new java.awt.Color(204, 204, 204));
        nombreCancionField.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        nombreAutorField.setBackground(new java.awt.Color(0, 0, 0));
        nombreAutorField.setForeground(new java.awt.Color(204, 204, 204));
        nombreAutorField.setCaretColor(new java.awt.Color(204, 204, 204));

        nombreCancionCancionesField.setBackground(new java.awt.Color(0, 0, 0));
        nombreCancionCancionesField.setForeground(new java.awt.Color(204, 204, 204));
        nombreCancionCancionesField.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        nombreAutorCancionesField.setBackground(new java.awt.Color(0, 0, 0));
        nombreAutorCancionesField.setForeground(new java.awt.Color(204, 204, 204));
        nombreAutorCancionesField.setCaretColor(new java.awt.Color(204, 204, 204));

        nombreDuracionField.setText("00:00:00");

        javax.swing.GroupLayout fondoColorLayout = new javax.swing.GroupLayout(fondoColor);
        fondoColor.setLayout(fondoColorLayout);
        fondoColorLayout.setHorizontalGroup(
            fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoColorLayout.createSequentialGroup()
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insertarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonEncender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoColorLayout.createSequentialGroup()
                                .addComponent(BotonFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonFechaBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoColorLayout.createSequentialGroup()
                                .addComponent(BotonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                                .addComponent(darkMode)))
                        .addGap(19, 19, 19))
                    .addGroup(fondoColorLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(BotonCommit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonConsultarAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonConsultarCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(fondoColorLayout.createSequentialGroup()
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(fondoColorLayout.createSequentialGroup()
                                .addComponent(consultaCancionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(consultaCancion))
                            .addComponent(consultarDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fondoColorLayout.createSequentialGroup()
                                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fondoColorLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nombreCancion)
                                            .addComponent(nombreAutor)))
                                    .addComponent(nombreNCanciones))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreCancionField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(nombreAutorField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(nombreNCancionesField)))
                            .addComponent(insertarDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addGroup(fondoColorLayout.createSequentialGroup()
                                .addComponent(consultaAutorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(consultaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotonDatosAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonConsultasPrepared, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(fondoColorLayout.createSequentialGroup()
                                    .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nombreCancionCanciones)
                                        .addComponent(nombreAutorCanciones)
                                        .addComponent(nombreDuracion))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nombreCancionCancionesField)
                                        .addComponent(nombreAutorCancionesField)
                                        .addComponent(nombreDuracionField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(insertarDatosCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotonDatosCanciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        fondoColorLayout.setVerticalGroup(
            fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEncender)
                    .addComponent(BotonApagar)
                    .addComponent(darkMode))
                .addGap(18, 18, 18)
                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonFecha)
                    .addComponent(BotonFechaBorrar))
                .addGap(18, 18, 18)
                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoColorLayout.createSequentialGroup()
                        .addComponent(insertarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreCancion)
                            .addComponent(nombreCancionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreAutor)
                            .addComponent(nombreAutorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreNCancionesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreNCanciones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonDatosAlbum))
                    .addGroup(fondoColorLayout.createSequentialGroup()
                        .addComponent(insertarDatosCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreCancionCanciones)
                            .addComponent(nombreCancionCancionesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreAutorCanciones)
                            .addComponent(nombreAutorCancionesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreDuracion)
                            .addComponent(nombreDuracionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonDatosCanciones)))
                .addGap(12, 12, 12)
                .addComponent(consultarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaCancionLabel)
                    .addComponent(consultaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaAutorLabel))
                .addGap(32, 32, 32)
                .addComponent(BotonConsultasPrepared)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(BotonConsultarCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonConsultarAlbum)
                    .addComponent(BotonCommit))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncenderActionPerformed
        gestor.iniciarConexion();
        if (gestor.iniciarConexion() == 0) {
            System.out.println("Conectado a la discografica");
            BotonEncender.setEnabled(false);
            BotonApagar.setEnabled(true);
            BotonFecha.setEnabled(true);
            BotonFechaBorrar.setEnabled(false);
            BotonDatosAlbum.setEnabled(true);
            BotonConsultarAlbum.setEnabled(true);
            BotonConsultarCanciones.setEnabled(true);
            BotonConsultasPrepared.setEnabled(true);
            BotonCommit.setEnabled(true);
            BotonDatosCanciones.setEnabled(true);
        } else {
            System.out.println("Error en la conexion de la BBDD");

        }


    }//GEN-LAST:event_BotonEncenderActionPerformed

    private void BotonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonApagarActionPerformed
        gestor.cerrarConexion();
        if (gestor.cerrarConexion() == 0) {
            System.out.println("Conexion cerrada correctamente");
            BotonApagar.setEnabled(false);
            BotonEncender.setEnabled(true);
            BotonFecha.setEnabled(false);
            BotonFechaBorrar.setEnabled(false);
            BotonDatosAlbum.setEnabled(false);
            BotonConsultarAlbum.setEnabled(false);
            BotonConsultarCanciones.setEnabled(false);
            BotonConsultasPrepared.setEnabled(false);
            BotonCommit.setEnabled(false);
            BotonDatosCanciones.setEnabled(false);
        } else {
            System.out.println("Error al cerrar la discorafica");
        }
    }//GEN-LAST:event_BotonApagarActionPerformed

    private void BotonFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFechaActionPerformed
        gestor.aniadirColumna();
        BotonFecha.setEnabled(false);
        BotonFechaBorrar.setEnabled(true);

    }//GEN-LAST:event_BotonFechaActionPerformed

    private void BotonFechaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFechaBorrarActionPerformed
        gestor.borrarColumna();
        BotonFechaBorrar.setEnabled(false);
        BotonFecha.setEnabled(true);


    }//GEN-LAST:event_BotonFechaBorrarActionPerformed

    private void darkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeActionPerformed

    }//GEN-LAST:event_darkModeActionPerformed

    private void darkModeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darkModeMousePressed
        if (darkMode.isSelected()) {
            fondoColor.setBackground(new java.awt.Color(204, 204, 204));
            BotonEncender.setBackground(new java.awt.Color(204, 204, 204));
            BotonEncender.setForeground(new java.awt.Color(0, 0, 0));
        } else {
            //Dark Mode
            fondoColor.setBackground(new java.awt.Color(102, 102, 102));

            BotonEncender.setBackground(new java.awt.Color(0, 0, 0));
            BotonEncender.setForeground(new java.awt.Color(204, 204, 204));

            BotonApagar.setBackground(new java.awt.Color(0, 0, 0));
            BotonApagar.setForeground(new java.awt.Color(204, 204, 204));

            BotonFecha.setBackground(new java.awt.Color(0, 0, 0));
            BotonFecha.setForeground(new java.awt.Color(204, 204, 204));

            BotonFechaBorrar.setBackground(new java.awt.Color(0, 0, 0));
            BotonFechaBorrar.setForeground(new java.awt.Color(204, 204, 204));

            BotonDatosAlbum.setBackground(new java.awt.Color(0, 0, 0));
            BotonDatosAlbum.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_darkModeMousePressed

    private void BotonDatosAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDatosAlbumActionPerformed
        gestor.insertarAlbum(nombreCancionField.getText(), nombreAutorField.getText(), nombreNCancionesField.getText());

    }//GEN-LAST:event_BotonDatosAlbumActionPerformed

    private void BotonConsultarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarAlbumActionPerformed
        
        salidaConsultasTexto.setText(gestor.consultaAlbumes());
        salidaConsultas.setVisible(true);

    }//GEN-LAST:event_BotonConsultarAlbumActionPerformed

    private void BotonConsultasPreparedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultasPreparedActionPerformed

        salidaConsultasTexto.setText(gestor.consulta_PreparedStatement(consultaAutor.getText()));
        salidaConsultas.setVisible(true);
    }//GEN-LAST:event_BotonConsultasPreparedActionPerformed

    private void BotonCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCommitActionPerformed
       gestor.insertarConCommit();
    }//GEN-LAST:event_BotonCommitActionPerformed

    private void BotonConsultarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarCancionesActionPerformed
        salidaConsultasTexto.setText(gestor.consultaCanciones());
        salidaConsultas.setVisible(true);
    }//GEN-LAST:event_BotonConsultarCancionesActionPerformed

    private void BotonDatosCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDatosCancionesActionPerformed
         gestor.insertarCancion(nombreCancionCancionesField.getText(), nombreAutorCancionesField.getText(), nombreDuracionField.getText());
    }//GEN-LAST:event_BotonDatosCancionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonApagar;
    private javax.swing.JButton BotonCommit;
    private javax.swing.JButton BotonConsultarAlbum;
    private javax.swing.JButton BotonConsultarCanciones;
    private javax.swing.JButton BotonConsultasPrepared;
    private javax.swing.JButton BotonDatosAlbum;
    private javax.swing.JButton BotonDatosCanciones;
    private javax.swing.JButton BotonEncender;
    private javax.swing.JButton BotonFecha;
    private javax.swing.JButton BotonFechaBorrar;
    private javax.swing.JTextField consultaAutor;
    private javax.swing.JLabel consultaAutorLabel;
    private javax.swing.JTextField consultaCancion;
    private javax.swing.JLabel consultaCancionLabel;
    private javax.swing.JLabel consultarDatos;
    private javax.swing.JToggleButton darkMode;
    private javax.swing.JPanel fondoColor;
    private javax.swing.JLabel insertarDatos;
    private javax.swing.JLabel insertarDatosCancion;
    private javax.swing.JLabel insertarFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreAutor;
    private javax.swing.JLabel nombreAutorCanciones;
    private javax.swing.JTextField nombreAutorCancionesField;
    private javax.swing.JTextField nombreAutorField;
    private javax.swing.JLabel nombreCancion;
    private javax.swing.JLabel nombreCancionCanciones;
    private javax.swing.JTextField nombreCancionCancionesField;
    private javax.swing.JTextField nombreCancionField;
    private javax.swing.JLabel nombreDuracion;
    private javax.swing.JTextField nombreDuracionField;
    private javax.swing.JLabel nombreNCanciones;
    private javax.swing.JTextField nombreNCancionesField;
    private javax.swing.JDialog salidaConsultas;
    private javax.swing.JTextArea salidaConsultasTexto;
    // End of variables declaration//GEN-END:variables
}
